# Generated by Django 4.0.1 on 2022-01-16 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(max_length=50)),
                ('lien_page', models.URLField(max_length=255, verbose_name="lien d'une page sans numéro")),
                ('nb_page', models.URLField(max_length=255, verbose_name='Nb de page à scraper')),
                ('selector_block', models.CharField(max_length=25, verbose_name="Selecteur CSS du bloack de l'annonce")),
                ('selector_img', models.CharField(max_length=25, verbose_name="Selecteur CSS d'image")),
                ('selector_titre', models.CharField(max_length=25, verbose_name='Selecteur CSS du titre')),
                ('selector_prix', models.CharField(max_length=25, verbose_name='Selecteur CSS du prix')),
                ('selector_ville', models.CharField(max_length=25, verbose_name='Selecteur CSS de la ville')),
                ('selector_date_pub', models.CharField(max_length=25, verbose_name='Selecteur CSS de la date de publication')),
            ],
            options={
                'verbose_name': 'Site de vente des smartphones',
                'verbose_name_plural': 'Site de vente des smartphones',
            },
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('date_pub', models.DateTimeField(null=True, verbose_name='Date  de publication')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.sites')),
            ],
            options={
                'verbose_name': 'Annonce de vente pour smartphone',
                'verbose_name_plural': 'Annonces de vente pour smartphone',
            },
        ),
    ]
