# Generated by Django 4.0.1 on 2022-01-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_sites_selector_lien_alter_sites_selector_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='nb_page',
            field=models.IntegerField(verbose_name='Nb de page à scraper'),
        ),
    ]
