# Generated by Django 4.0.1 on 2022-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phones_create_at_phones_lien_pub_phones_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date  de creation'),
        ),
        migrations.AlterField(
            model_name='phones',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date  de la derniere MAJ'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date  de creation'),
        ),
        migrations.AlterField(
            model_name='sites',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date  de la derniere MAJ'),
        ),
    ]
