# Generated by Django 4.0.1 on 2022-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phones_create_at_alter_phones_update_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='image',
            field=models.URLField(max_length=255, verbose_name="lien photos de l'annonce"),
        ),
        migrations.AlterField(
            model_name='phones',
            name='lien_pub',
            field=models.URLField(null=True, verbose_name="lien de l'annonce"),
        ),
    ]
