# Generated by Django 4.0.1 on 2022-01-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_phones_image_alter_phones_lien_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='date_pub',
            field=models.CharField(max_length=100, null=True, verbose_name='Date  de publication'),
        ),
    ]
