# Generated by Django 4.0.1 on 2022-01-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_phones_date_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='lien_pub',
            field=models.URLField(unique=True, verbose_name="lien de l'annonce"),
        ),
        migrations.AlterField(
            model_name='phones',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
